<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">

<!--<!DOCTYPE students [

		<!ELEMENT students (student+) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT gender (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>
		]>
-->

<students>

    <student number="s001">
        <name>zhangsan</name>
        <age>abc</age>
        <gender>hehe</gender>
    </student>

    <student number="s002">
        <name>lisi</name>
        <age>24</age>
        <gender>female</gender>
    </student>

</students>